from typing import List, TypedDict, Optional, Any
from langchain_community.vectorstores import FAISS
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    """Represents the state of our agent at each step."""
    
    input: str
    """The user's initial query."""
    
    chat_history: List[BaseMessage]
    """The history of the conversation."""
    
    # --- Information Retrieval ---
    retrieved_docs: List[Any]
    """Documents retrieved from all sources (user file, support DB, financial DB)."""
    
    # --- Document Processing ---
    document_db: Optional[FAISS]
    """The vector database created from a user-uploaded document."""
    
    supporting_db: FAISS
    """The vector database for public support programs."""

    financial_db: Optional[FAISS]
    """The vector database for financial products."""

    # --- Generated Response ---
    generated_answer: str
    """The final answer generated by the LLM."""
